name: CD Progress
on:
  push:
    branches: [master]
jobs:
  build-and-send-to-telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Execute Gradle
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload to Telegram Bot
        run: |
          cd android/app/build/outputs/apk/release/
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F text='App is Released!' ${{secrets.TG_BOT_TOKEN}}/sendMessage
          curl -X POST -H 'Content-Type: multipart/form-data' -F "chat_id=${{secrets.TG_CHAT_ID}}" -F document=@app-release.apk ${{secrets.TG_BOT_TOKEN}}/sendDocument
